# Generated by Django 3.1.1 on 2020-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(verbose_name='search date')),
                ('search_term', models.TextField(max_length=200)),
            ],
        ),
    ]
