# Generated by Django 3.1.1 on 2020-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='search_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='search_term',
            field=models.TextField(max_length=60),
        ),
    ]
